skip_if_exists: true
know_privacy_key: false

# Parallelism
parallel_num: 20
each_run_num: 2

# Tool settings
attack_tool:
  - target

# Injection strategy
injection_method: direct_prompt_injection

# Logging / storage
write_db: false

# Task control
task_num: 5
run_tools_num: 2

# LLMs under evaluation
llms:
  - qwen3

attack_types:
  pure:
    steal_parmas_num: [1]
    defense_type:
      - null
      - dynamic_prompt_rewriting
      - soft_prompt_defense
      - soft_prompt_defense_dynamic_prompt_rewriting
  
  naive:
    steal_parmas_num: [0,1,2,3,4,5,6,7,8,9]
    defense_type:
      - null
      - dynamic_prompt_rewriting